version: '3.8'

services:
  mlflow-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
